# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
mediumPuzzle = Puzzle.create(difficulty: 'Medium', completed: false)

across1 = Clue.create(puzzle: mediumPuzzle, number: 1, word: 'DALI', direction: 'across', hint: 'Painter of melting pocket watches')
across5 = Clue.create(puzzle: mediumPuzzle, number: 5, word: 'ROB', direction: 'across', hint: 'Stick up')
across8 = Clue.create(puzzle: mediumPuzzle, number: 8, word: 'CZECHS', direction: 'across', hint: 'Neighbor of Poles')
across14 = Clue.create(puzzle: mediumPuzzle, number: 14, word: 'ANAPHORA', direction: 'across', hint: 'Repetition of words at the starts of successive phrases, in rhetoric')
across16 = Clue.create(puzzle: mediumPuzzle, number: 16, word: 'PROSHOP', direction: 'across', hint: 'Place to find a driver')
across17 = Clue.create(puzzle: mediumPuzzle, number: 17, word: 'BECHAMEL', direction: 'across', hint: 'French white sauce')
across18 = Clue.create(puzzle: mediumPuzzle, number: 18, word: 'EONLINE', direction: 'across', hint: 'Celebrity gossip site')
across19 = Clue.create(puzzle: mediumPuzzle, number: 19, word: 'MOORE', direction: 'across', hint: 'Michael who directed "Fahrenheit 9/11"')
across20 = Clue.create(puzzle: mediumPuzzle, number: 20, word: 'ISSUE', direction: 'across', hint: 'Something to debate')
across22 = Clue.create(puzzle: mediumPuzzle, number: 22, word: 'PEA', direction: 'across', hint: 'One might have a black eye')
across23 = Clue.create(puzzle: mediumPuzzle, number: 23, word: 'POSTDOC', direction: 'across', hint: 'Aspiring prof, maybe')
across25 = Clue.create(puzzle: mediumPuzzle, number: 25, word: 'TOP', direction: 'across', hint: 'Bunk bed option')
across26 = Clue.create(puzzle: mediumPuzzle, number: 26, word: 'USSR', direction: 'across', hint: 'The Beatles\' "Back in the ___')
across27 = Clue.create(puzzle: mediumPuzzle, number: 27, word: 'INTO', direction: 'across', hint: 'Passionate about')
across28 = Clue.create(puzzle: mediumPuzzle, number: 28, word: 'OPUS', direction: 'across', hint: 'Numbered compostion')
across30 = Clue.create(puzzle: mediumPuzzle, number: 30, word: 'GRIT', direction: 'across', hint: 'Stick-to-it-iveness')
across31 = Clue.create(puzzle: mediumPuzzle, number: 31, word: 'TEE', direction: 'across', hint: 'Shorts go-with')
across32 = Clue.create(puzzle: mediumPuzzle, number: 32, word: 'DECAF', direction: 'across', hint: 'Late-night Starbucks choice')
across34 = Clue.create(puzzle: mediumPuzzle, number: 34, word: 'SIGN', direction: 'across', hint: 'Omen')
across35 = Clue.create(puzzle: mediumPuzzle, number: 35, word: 'CAMOUFLAGE', direction: 'across', hint: '"Trick" used by the creatures found in rows 3, 5, 11 and 13', joined: true)
across37 = Clue.create(puzzle: mediumPuzzle, number: 37, word: 'TODO', direction: 'across', hint: 'Checklist heading')
across38 = Clue.create(puzzle: mediumPuzzle, number: 38, word: 'LEAPS', direction: 'across', hint: 'LEAPS')
across39 = Clue.create(puzzle: mediumPuzzle, number: 39, word: 'ADD', direction: 'across', hint: 'Tack (on)')
across42 = Clue.create(puzzle: mediumPuzzle, number: 42, word: 'AIDS', direction: 'across', hint: 'Helps')
across43 = Clue.create(puzzle: mediumPuzzle, number: 43, word: 'LIDS', direction: 'across', hint: 'Targets for some eye makeup')
across44 = Clue.create(puzzle: mediumPuzzle, number: 44, word: 'ALOE', direction: 'across', hint: 'Spiky yet soothing plant')
across45 = Clue.create(puzzle: mediumPuzzle, number: 45, word: 'PLEA', direction: 'across', hint: 'Fund-raising letter, e.g.')
across46 = Clue.create(puzzle: mediumPuzzle, number: 46, word: 'FIN', direction: 'across', hint: 'Bit of scuba equipment')
across47 = Clue.create(puzzle: mediumPuzzle, number: 47, word: 'SECTION', direction: 'across', hint: 'Stadium ticket info')
across50 = Clue.create(puzzle: mediumPuzzle, number: 50, word: 'AKC', direction: 'across', hint: 'Org. that recognizes nearly 200 breeds')
across51 = Clue.create(puzzle: mediumPuzzle, number: 51, word: 'CREEL', direction: 'across', hint: 'Fishing basket')
across53 = Clue.create(puzzle: mediumPuzzle, number: 53, word: 'GAMER', direction: 'across', hint: 'Fortnite devotee, e.g.')
across54 = Clue.create(puzzle: mediumPuzzle, number: 54, word: 'GALILEO', direction: 'across', hint: 'Astronomer who first observed Saturn\'s rings')
across56 = Clue.create(puzzle: mediumPuzzle, number: 56, word: 'PARDONME', direction: 'across', hint: 'Sorry!')
across59 = Clue.create(puzzle: mediumPuzzle, number: 59, word: 'ELISION', direction: 'across', hint: 'Feature of "G\'day" or "Yes\'m"')
across60 = Clue.create(puzzle: mediumPuzzle, number: 60, word: 'GOESSTAG', direction: 'across', hint: 'Attends without a date, say')
across61 = Clue.create(puzzle: mediumPuzzle, number: 61, word: 'SIPHON', direction: 'across', hint: 'Gas thief\'s device')
across62 = Clue.create(puzzle: mediumPuzzle, number: 62, word: 'ALT', direction: 'across', hint: 'Key near Ctrl')
across63 = Clue.create(puzzle: mediumPuzzle, number: 63, word: 'TOTO', direction: 'across', hint: 'Dog on the yellow brick road')


down1 = Clue.create(puzzle: mediumPuzzle, number: 1, word: 'DAB', direction: 'down', hint: 'Modern dance move')
down2 = Clue.create(puzzle: mediumPuzzle, number: 2, word: 'ANEMONE', direction: 'down', hint: 'Sea ___ (tide pool dweller)')
down3 = Clue.create(puzzle: mediumPuzzle, number: 3, word: 'LACOSTE', direction: 'down', hint: 'Polo shirt brand')
down4 = Clue.create(puzzle: mediumPuzzle, number: 4, word: 'IPHOTO', direction: 'down', hint: 'Longtime Apple program whose icon featured a camera')
down5 = Clue.create(puzzle: mediumPuzzle, number: 5, word: 'ROMEO', direction: 'down', hint: 'Amorous Guy')
down6 = Clue.create(puzzle: mediumPuzzle, number: 6, word: 'ORE', direction: 'down', hint: 'Mine car filler')
down7 = Clue.create(puzzle: mediumPuzzle, number: 7, word: 'BALI', direction: 'down', hint: 'Island with volcanoes and rice paddies')
down8 = Clue.create(puzzle: mediumPuzzle, number: 8, word: 'CROUP', direction: 'down', hint: 'Infant\'s ailment')
down9 = Clue.create(puzzle: mediumPuzzle, number: 9, word: 'ZONE', direction: 'down', hint: 'The "Z" of ZIP code')
down10 = Clue.create(puzzle: mediumPuzzle, number: 10, word: 'ESL', direction: 'down', hint: 'Fluency-building subj.')
down11= Clue.create(puzzle: mediumPuzzle, number: 11, word: 'CHIPSIN', direction: 'down', hint: 'Contributes a little')
down12 = Clue.create(puzzle: mediumPuzzle, number: 12, word: 'HONEST', direction: 'down', hint: '"No Lie!"')
down13 = Clue.create(puzzle: mediumPuzzle, number: 13, word: 'SPEAR', direction: 'down', hint: 'Caveman\'s weapon')
down15 = Clue.create(puzzle: mediumPuzzle, number: 15, word: 'HARD', direction: 'down', hint: 'Tough')
down16 = Clue.create(puzzle: mediumPuzzle, number: 16, word: 'PESOS', direction: 'down', hint: 'Columbian coins')
down21 = Clue.create(puzzle: mediumPuzzle, number: 21, word: 'STUFFED', direction: 'down', hint: 'Like some peppers and ballot boxes')
down23 = Clue.create(puzzle: mediumPuzzle, number: 23, word: 'PIT', direction: 'down', hint: 'Ball ___ (play area)')
down24 = Clue.create(puzzle: mediumPuzzle, number: 24, word: 'COCO', direction: 'down', hint: '2017 Disney/Pixar film set in the Land of the Dead')
down26 = Clue.create(puzzle: mediumPuzzle, number: 26, word: 'URGE', direction: 'down', hint: 'Strong Desire')
down29 = Clue.create(puzzle: mediumPuzzle, number: 29, word: 'PAULINE', direction: 'down', hint: 'Film critic Kael')
down30 = Clue.create(puzzle: mediumPuzzle, number: 30, word: 'GIGS', direction: 'down', hint: 'Parties, e.g., for D.J.s')
down32 = Clue.create(puzzle: mediumPuzzle, number: 32, word: 'DADS', direction: 'down', hint: 'Some diaper changers')
down33 = Clue.create(puzzle: mediumPuzzle, number: 33, word: 'EMO', direction: 'down', hint: 'Genre for Fall Out Boy')
down34 = Clue.create(puzzle: mediumPuzzle, number: 34, word: 'SAP', direction: 'down', hint: 'It sticks to a trunk')
down35 = Clue.create(puzzle: mediumPuzzle, number: 35, word: 'CODA', direction: 'down', hint: 'Musical finale')
down36 = Clue.create(puzzle: mediumPuzzle, number: 36, word: 'LASS', direction: 'down', hint: 'Girl in a bonnet, maybe')
down37 = Clue.create(puzzle: mediumPuzzle, number: 37, word: 'TIECLIP', direction: 'down', hint: 'Haberdasher\'s accessory')
down39 = Clue.create(puzzle: mediumPuzzle, number: 39, word: 'ALIENTO', direction: 'down', hint: 'Not recognizable by')
down40 = Clue.create(puzzle: mediumPuzzle, number: 40, word: 'DOORMAT', direction: 'down', hint: 'One might say "Welcome"')
down41 = Clue.create(puzzle: mediumPuzzle, number: 41, word: 'DEN', direction: 'down', hint: 'Place to hibernate')
down42 = Clue.create(puzzle: mediumPuzzle, number: 42, word: 'ALKALI', direction: 'down', hint: 'High-pH compound')
down43 = Clue.create(puzzle: mediumPuzzle, number: 43, word: 'LIEON', direction: 'down', hint: 'Use, as a mattress')
down44 = Clue.create(puzzle: mediumPuzzle, number: 44, word: 'ATMOST', direction: 'down', hint: 'No more than')
down45 = Clue.create(puzzle: mediumPuzzle, number: 45, word: 'PAGES', direction: 'down', hint: 'Leaves at the library?')
down46 = Clue.create(puzzle: mediumPuzzle, number: 46, word: 'FREON', direction: 'down', hint: 'Air-conditioning coolant')
down48 = Clue.create(puzzle: mediumPuzzle, number: 48, word: 'EGRET', direction: 'down', hint: 'Bird known for its plumes')
down49 = Clue.create(puzzle: mediumPuzzle, number: 49, word: 'CADS', direction: 'down', hint: 'Scoundrels')
down51 = Clue.create(puzzle: mediumPuzzle, number: 51, word: 'CLIO', direction: 'down', hint: 'Muse of history')
down52 = Clue.create(puzzle: mediumPuzzle, number: 52, word: 'LPGA', direction: 'down', hint: 'Michelle Wie\'s org.')
down55 = Clue.create(puzzle: mediumPuzzle, number: 55, word: 'ISH', direction: 'down', hint: 'Kinda sorta')
down57 = Clue.create(puzzle: mediumPuzzle, number: 57, word: 'AOL', direction: 'down', hint: 'Part of Verizon Media')
down58 = Clue.create(puzzle: mediumPuzzle, number: 58, word: 'EGO', direction: 'down', hint: '___-surf (Google yourself)')


mediumPuzzle.cells.create(letter: 'D', index: 1, across_word: across1.id, down_word: down1.id)
mediumPuzzle.cells.create(letter: 'A', index: 2, across_word: across1.id, down_word: down2.id)
mediumPuzzle.cells.create(letter: 'L', index: 3, across_word: across1.id, down_word: down3.id)
mediumPuzzle.cells.create(letter: 'I', index: 4, across_word: across1.id, down_word: down4.id)
mediumPuzzle.cells.create(letter: '!', index: 5, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'R', index: 6, across_word: across5.id, down_word: down5.id)
mediumPuzzle.cells.create(letter: 'O', index: 7, across_word: across5.id, down_word: down6.id)
mediumPuzzle.cells.create(letter: 'B', index: 8, across_word: across5.id, down_word: down7.id)
mediumPuzzle.cells.create(letter: '!', index: 9, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 10, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'C', index: 11, across_word: across8.id, down_word: down8.id)
mediumPuzzle.cells.create(letter: 'Z', index: 12, across_word: across8.id, down_word: down9.id)
mediumPuzzle.cells.create(letter: 'E', index: 13, across_word: across8.id, down_word: down10.id)
mediumPuzzle.cells.create(letter: 'C', index: 14, across_word: across8.id, down_word: down11.id)
mediumPuzzle.cells.create(letter: 'H', index: 15, across_word: across8.id, down_word: down12.id)
mediumPuzzle.cells.create(letter: 'S', index: 16, across_word: across8.id, down_word: down13.id)
mediumPuzzle.cells.create(letter: 'A', index: 17, across_word: across14.id, down_word: down1.id)
mediumPuzzle.cells.create(letter: 'N', index: 18, across_word: across14.id, down_word: down2.id)
mediumPuzzle.cells.create(letter: 'A', index: 19, across_word: across14.id, down_word: down3.id)
mediumPuzzle.cells.create(letter: 'P', index: 20, across_word: across14.id, down_word: down4.id)
mediumPuzzle.cells.create(letter: 'H', index: 21, across_word: across14.id, down_word: down15.id)
mediumPuzzle.cells.create(letter: 'O', index: 22, across_word: across14.id, down_word: down5.id)
mediumPuzzle.cells.create(letter: 'R', index: 23, across_word: across14.id, down_word: down6.id)
mediumPuzzle.cells.create(letter: 'A', index: 24, across_word: across14.id, down_word: down7.id)
mediumPuzzle.cells.create(letter: '!', index: 25, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'P', index: 26, across_word: across16.id, down_word: down16.id)
mediumPuzzle.cells.create(letter: 'R', index: 27, across_word: across16.id, down_word: down8.id)
mediumPuzzle.cells.create(letter: 'O', index: 28, across_word: across16.id, down_word: down9.id)
mediumPuzzle.cells.create(letter: 'S', index: 29, across_word: across16.id, down_word: down10.id)
mediumPuzzle.cells.create(letter: 'H', index: 30, across_word: across16.id, down_word: down11.id)
mediumPuzzle.cells.create(letter: 'O', index: 31, across_word: across16.id, down_word: down12.id)
mediumPuzzle.cells.create(letter: 'P', index: 32, across_word: across16.id, down_word: down13.id)
mediumPuzzle.cells.create(letter: 'B', index: 33, across_word: across17.id, down_word: down1.id)
mediumPuzzle.cells.create(letter: 'E', index: 34, across_word: across17.id, down_word: down2.id)
mediumPuzzle.cells.create(letter: 'C', index: 35, across_word: across17.id, down_word: down3.id)
mediumPuzzle.cells.create(letter: 'H', index: 36, across_word: across17.id, down_word: down4.id)
mediumPuzzle.cells.create(letter: 'A', index: 37, across_word: across17.id, down_word: down15.id)
mediumPuzzle.cells.create(letter: 'M', index: 38, across_word: across17.id, down_word: down5.id)
mediumPuzzle.cells.create(letter: 'E', index: 39, across_word: across17.id, down_word: down6.id)
mediumPuzzle.cells.create(letter: 'L', index: 40, across_word: across17.id, down_word: down7.id)
mediumPuzzle.cells.create(letter: '!', index: 41, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'E', index: 42, across_word: across18.id, down_word: down16.id)
mediumPuzzle.cells.create(letter: 'O', index: 43, across_word: across18.id, down_word: down8.id)
mediumPuzzle.cells.create(letter: 'N', index: 44, across_word: across18.id, down_word: down9.id)
mediumPuzzle.cells.create(letter: 'L', index: 45, across_word: across18.id, down_word: down10.id)
mediumPuzzle.cells.create(letter: 'I', index: 46, across_word: across18.id, down_word: down11.id)
mediumPuzzle.cells.create(letter: 'N', index: 47, across_word: across18.id, down_word: down12.id)
mediumPuzzle.cells.create(letter: 'E', index: 48, across_word: across18.id, down_word: down13.id)
mediumPuzzle.cells.create(letter: '!', index: 49, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'M', index: 50, across_word: across19.id, down_word: down2.id)
mediumPuzzle.cells.create(letter: 'O', index: 51, across_word: across19.id, down_word: down3.id)
mediumPuzzle.cells.create(letter: 'O', index: 52, across_word: across19.id, down_word: down4.id)
mediumPuzzle.cells.create(letter: 'R', index: 53, across_word: across19.id, down_word: down15.id)
mediumPuzzle.cells.create(letter: 'E', index: 54, across_word: across19.id, down_word: down5.id)
mediumPuzzle.cells.create(letter: '!', index: 55, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'I', index: 56, across_word: across20.id, down_word: down7.id)
mediumPuzzle.cells.create(letter: 'S', index: 57, across_word: across20.id, down_word: down21.id)
mediumPuzzle.cells.create(letter: 'S', index: 58, across_word: across20.id, down_word: down16.id)
mediumPuzzle.cells.create(letter: 'U', index: 59, across_word: across20.id, down_word: down8.id)
mediumPuzzle.cells.create(letter: 'E', index: 60, across_word: across20.id, down_word: down9.id)
mediumPuzzle.cells.create(letter: '!', index: 61, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'P', index: 62, across_word: across22.id, down_word: down11.id)
mediumPuzzle.cells.create(letter: 'E', index: 63, across_word: across22.id, down_word: down12.id)
mediumPuzzle.cells.create(letter: 'A', index: 64, across_word: across22.id, down_word: down13.id)
mediumPuzzle.cells.create(letter: 'P', index: 65, across_word: across23.id, down_word: down23.id)
mediumPuzzle.cells.create(letter: 'O', index: 66, across_word: across23.id, down_word: down2.id)
mediumPuzzle.cells.create(letter: 'S', index: 67, across_word: across23.id, down_word: down3.id)
mediumPuzzle.cells.create(letter: 'T', index: 68, across_word: across23.id, down_word: down4.id)
mediumPuzzle.cells.create(letter: 'D', index: 69, across_word: across23.id, down_word: down15.id)
mediumPuzzle.cells.create(letter: 'O', index: 70, across_word: across23.id, down_word: down5.id)
mediumPuzzle.cells.create(letter: 'C', index: 71, across_word: across23.id, down_word: down24.id)
mediumPuzzle.cells.create(letter: '!', index: 72, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'T', index: 73, across_word: across25.id, down_word: down21.id)
mediumPuzzle.cells.create(letter: 'O', index: 74, across_word: across25.id, down_word: down16.id)
mediumPuzzle.cells.create(letter: 'P', index: 75, across_word: across25.id, down_word: down8.id)
mediumPuzzle.cells.create(letter: '!', index: 76, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'U', index: 77, across_word: across26.id, down_word: down26.id)
mediumPuzzle.cells.create(letter: 'S', index: 78, across_word: across26.id, down_word: down11.id)
mediumPuzzle.cells.create(letter: 'S', index: 79, across_word: across26.id, down_word: down12.id)
mediumPuzzle.cells.create(letter: 'R', index: 80, across_word: across26.id, down_word: down13.id)
mediumPuzzle.cells.create(letter: 'I', index: 81, across_word: across27.id, down_word: down23.id)
mediumPuzzle.cells.create(letter: 'N', index: 82, across_word: across27.id, down_word: down2.id)
mediumPuzzle.cells.create(letter: 'T', index: 83, across_word: across27.id, down_word: down3.id)
mediumPuzzle.cells.create(letter: 'O', index: 84, across_word: across27.id, down_word: down4.id)
mediumPuzzle.cells.create(letter: '!', index: 85, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 86, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'O', index: 87, across_word: across28.id, down_word: down24.id)
mediumPuzzle.cells.create(letter: 'P', index: 88, across_word: across28.id, down_word: down29.id)
mediumPuzzle.cells.create(letter: 'U', index: 89, across_word: across28.id, down_word: down21.id)
mediumPuzzle.cells.create(letter: 'S', index: 90, across_word: across28.id, down_word: down16.id)
mediumPuzzle.cells.create(letter: '!', index: 91, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'G', index: 92, across_word: across30.id, down_word: down30.id)
mediumPuzzle.cells.create(letter: 'R', index: 93, across_word: across30.id, down_word: down26.id)
mediumPuzzle.cells.create(letter: 'I', index: 94, across_word: across30.id, down_word: down11.id)
mediumPuzzle.cells.create(letter: 'T', index: 95, across_word: across30.id, down_word: down12.id)
mediumPuzzle.cells.create(letter: '!', index: 96, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'T', index: 97, across_word: across31.id, down_word: down23.id)
mediumPuzzle.cells.create(letter: 'E', index: 98, across_word: across31.id, down_word: down2.id)
mediumPuzzle.cells.create(letter: 'E', index: 99, across_word: across31.id, down_word: down3.id)
mediumPuzzle.cells.create(letter: '!', index: 100, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'D', index: 101, across_word: across32.id, down_word: down32.id)
mediumPuzzle.cells.create(letter: 'E', index: 102, across_word: across32.id, down_word: down33.id)
mediumPuzzle.cells.create(letter: 'C', index: 103, across_word: across32.id, down_word: down24.id)
mediumPuzzle.cells.create(letter: 'A', index: 104, across_word: across32.id, down_word: down29.id)
mediumPuzzle.cells.create(letter: 'F', index: 105, across_word: across32.id, down_word: down21.id)
mediumPuzzle.cells.create(letter: '!', index: 106, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'S', index: 107, across_word: across34.id, down_word: down34.id)
mediumPuzzle.cells.create(letter: 'I', index: 108, across_word: across34.id, down_word: down30.id)
mediumPuzzle.cells.create(letter: 'G', index: 109, across_word: across34.id, down_word: down26.id)
mediumPuzzle.cells.create(letter: 'N', index: 110, across_word: across34.id, down_word: down11.id)
mediumPuzzle.cells.create(letter: '!', index: 111, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 112, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 113, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 114, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 115, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'C', index: 116, across_word: across35.id, down_word: down35.id)
mediumPuzzle.cells.create(letter: 'A', index: 117, across_word: across35.id, down_word: down32.id)
mediumPuzzle.cells.create(letter: 'M', index: 118, across_word: across35.id, down_word: down33.id)
mediumPuzzle.cells.create(letter: 'O', index: 119, across_word: across35.id, down_word: down24.id)
mediumPuzzle.cells.create(letter: 'U', index: 120, across_word: across35.id, down_word: down29.id)
mediumPuzzle.cells.create(letter: 'F', index: 121, across_word: across35.id, down_word: down21.id)
mediumPuzzle.cells.create(letter: 'L', index: 122, across_word: across35.id, down_word: down36.id)
mediumPuzzle.cells.create(letter: 'A', index: 123, across_word: across35.id, down_word: down34.id)
mediumPuzzle.cells.create(letter: 'G', index: 124, across_word: across35.id, down_word: down30.id)
mediumPuzzle.cells.create(letter: 'E', index: 125, across_word: across35.id, down_word: down26.id)
mediumPuzzle.cells.create(letter: '!', index: 126, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 127, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 128, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 129, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 130, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'T', index: 131, across_word: across37.id, down_word: down37.id)
mediumPuzzle.cells.create(letter: 'O', index: 132, across_word: across37.id, down_word: down35.id)
mediumPuzzle.cells.create(letter: 'D', index: 133, across_word: across37.id, down_word: down32.id)
mediumPuzzle.cells.create(letter: 'O', index: 134, across_word: across37.id, down_word: down33.id)
mediumPuzzle.cells.create(letter: '!', index: 135, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'L', index: 136, across_word: across38.id, down_word: down29.id)
mediumPuzzle.cells.create(letter: 'E', index: 137, across_word: across38.id, down_word: down21.id)
mediumPuzzle.cells.create(letter: 'A', index: 138, across_word: across38.id, down_word: down36.id)
mediumPuzzle.cells.create(letter: 'P', index: 139, across_word: across38.id, down_word: down34.id)
mediumPuzzle.cells.create(letter: 'S', index: 140, across_word: across38.id, down_word: down30.id)
mediumPuzzle.cells.create(letter: '!', index: 141, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'A', index: 142, across_word: across39.id, down_word: down39.id)
mediumPuzzle.cells.create(letter: 'D', index: 143, across_word: across39.id, down_word: down40.id)
mediumPuzzle.cells.create(letter: 'D', index: 144, across_word: across39.id, down_word: down41.id)
mediumPuzzle.cells.create(letter: '!', index: 145, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'A', index: 146, across_word: across42.id, down_word: down42.id)
mediumPuzzle.cells.create(letter: 'I', index: 147, across_word: across42.id, down_word: down37.id)
mediumPuzzle.cells.create(letter: 'D', index: 148, across_word: across42.id, down_word: down35.id)
mediumPuzzle.cells.create(letter: 'S', index: 149, across_word: across42.id, down_word: down32.id)
mediumPuzzle.cells.create(letter: '!', index: 150, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'L', index: 151, across_word: across43.id, down_word: down43.id)
mediumPuzzle.cells.create(letter: 'I', index: 152, across_word: across43.id, down_word: down29.id)
mediumPuzzle.cells.create(letter: 'D', index: 153, across_word: across43.id, down_word: down21.id)
mediumPuzzle.cells.create(letter: 'S', index: 154, across_word: across43.id, down_word: down36.id)
mediumPuzzle.cells.create(letter: '!', index: 155, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 156, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'A', index: 157, across_word: across44.id, down_word: down44.id)
mediumPuzzle.cells.create(letter: 'L', index: 158, across_word: across44.id, down_word: down39.id)
mediumPuzzle.cells.create(letter: 'O', index: 159, across_word: across44.id, down_word: down40.id)
mediumPuzzle.cells.create(letter: 'E', index: 160, across_word: across44.id, down_word: down41.id)
mediumPuzzle.cells.create(letter: 'P', index: 161, across_word: across45.id, down_word: down45.id)
mediumPuzzle.cells.create(letter: 'L', index: 162, across_word: across45.id, down_word: down42.id)
mediumPuzzle.cells.create(letter: 'E', index: 163, across_word: across45.id, down_word: down37.id)
mediumPuzzle.cells.create(letter: 'A', index: 164, across_word: across45.id, down_word: down35.id)
mediumPuzzle.cells.create(letter: '!', index: 165, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'F', index: 166, across_word: across46.id, down_word: down46.id)
mediumPuzzle.cells.create(letter: 'I', index: 167, across_word: across46.id, down_word: down43.id)
mediumPuzzle.cells.create(letter: 'N', index: 168, across_word: across46.id, down_word: down29.id)
mediumPuzzle.cells.create(letter: '!', index: 169, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'S', index: 170, across_word: across47.id, down_word: down36.id)
mediumPuzzle.cells.create(letter: 'E', index: 171, across_word: across47.id, down_word: down48.id)
mediumPuzzle.cells.create(letter: 'C', index: 172, across_word: across47.id, down_word: down49.id)
mediumPuzzle.cells.create(letter: 'T', index: 173, across_word: across47.id, down_word: down44.id)
mediumPuzzle.cells.create(letter: 'I', index: 174, across_word: across47.id, down_word: down39.id)
mediumPuzzle.cells.create(letter: 'O', index: 175, across_word: across47.id, down_word: down40.id)
mediumPuzzle.cells.create(letter: 'N', index: 176, across_word: across47.id, down_word: down41.id)
mediumPuzzle.cells.create(letter: 'A', index: 177, across_word: across50.id, down_word: down45.id)
mediumPuzzle.cells.create(letter: 'K', index: 178, across_word: across50.id, down_word: down42.id)
mediumPuzzle.cells.create(letter: 'C', index: 179, across_word: across50.id, down_word: down37.id)
mediumPuzzle.cells.create(letter: '!', index: 180, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'C', index: 181, across_word: across51.id, down_word: down51.id)
mediumPuzzle.cells.create(letter: 'R', index: 182, across_word: across51.id, down_word: down46.id)
mediumPuzzle.cells.create(letter: 'E', index: 183, across_word: across51.id, down_word: down43.id)
mediumPuzzle.cells.create(letter: 'E', index: 184, across_word: across51.id, down_word: down29.id)
mediumPuzzle.cells.create(letter: 'L', index: 185, across_word: across51.id, down_word: down52.id)
mediumPuzzle.cells.create(letter: '!', index: 186, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'G', index: 187, across_word: across53.id, down_word: down48.id)
mediumPuzzle.cells.create(letter: 'A', index: 188, across_word: across53.id, down_word: down49.id)
mediumPuzzle.cells.create(letter: 'M', index: 189, across_word: across53.id, down_word: down44.id)
mediumPuzzle.cells.create(letter: 'E', index: 190, across_word: across53.id, down_word: down39.id)
mediumPuzzle.cells.create(letter: 'R', index: 191, across_word: across53.id, down_word: down40.id)
mediumPuzzle.cells.create(letter: '!', index: 192, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'G', index: 193, across_word: across54.id, down_word: down45.id)
mediumPuzzle.cells.create(letter: 'A', index: 194, across_word: across54.id, down_word: down42.id)
mediumPuzzle.cells.create(letter: 'L', index: 195, across_word: across54.id, down_word: down37.id)
mediumPuzzle.cells.create(letter: 'I', index: 196, across_word: across54.id, down_word: down55.id)
mediumPuzzle.cells.create(letter: 'L', index: 197, across_word: across54.id, down_word: down51.id)
mediumPuzzle.cells.create(letter: 'E', index: 198, across_word: across54.id, down_word: down46.id)
mediumPuzzle.cells.create(letter: 'O', index: 199, across_word: across54.id, down_word: down43.id)
mediumPuzzle.cells.create(letter: '!', index: 200, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'P', index: 201, across_word: across56.id, down_word: down52.id)
mediumPuzzle.cells.create(letter: 'A', index: 202, across_word: across56.id, down_word: down57.id)
mediumPuzzle.cells.create(letter: 'R', index: 203, across_word: across56.id, down_word: down48.id)
mediumPuzzle.cells.create(letter: 'D', index: 204, across_word: across56.id, down_word: down49.id)
mediumPuzzle.cells.create(letter: 'O', index: 205, across_word: across56.id, down_word: down44.id)
mediumPuzzle.cells.create(letter: 'N', index: 206, across_word: across56.id, down_word: down39.id)
mediumPuzzle.cells.create(letter: 'M', index: 207, across_word: across56.id, down_word: down40.id)
mediumPuzzle.cells.create(letter: 'E', index: 208, across_word: across56.id, down_word: down58.id)
mediumPuzzle.cells.create(letter: 'E', index: 209, across_word: across59.id, down_word: down45.id)
mediumPuzzle.cells.create(letter: 'L', index: 210, across_word: across59.id, down_word: down42.id)
mediumPuzzle.cells.create(letter: 'I', index: 211, across_word: across59.id, down_word: down37.id)
mediumPuzzle.cells.create(letter: 'S', index: 212, across_word: across59.id, down_word: down55.id)
mediumPuzzle.cells.create(letter: 'I', index: 213, across_word: across59.id, down_word: down51.id)
mediumPuzzle.cells.create(letter: 'O', index: 214, across_word: across59.id, down_word: down46.id)
mediumPuzzle.cells.create(letter: 'N', index: 215, across_word: across59.id, down_word: down43.id)
mediumPuzzle.cells.create(letter: '!', index: 216, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'G', index: 217, across_word: across60.id, down_word: down52.id)
mediumPuzzle.cells.create(letter: 'O', index: 218, across_word: across60.id, down_word: down57.id)
mediumPuzzle.cells.create(letter: 'E', index: 219, across_word: across60.id, down_word: down48.id)
mediumPuzzle.cells.create(letter: 'S', index: 220, across_word: across60.id, down_word: down49.id)
mediumPuzzle.cells.create(letter: 'S', index: 221, across_word: across60.id, down_word: down44.id)
mediumPuzzle.cells.create(letter: 'T', index: 222, across_word: across60.id, down_word: down39.id)
mediumPuzzle.cells.create(letter: 'A', index: 223, across_word: across60.id, down_word: down40.id)
mediumPuzzle.cells.create(letter: 'G', index: 224, across_word: across60.id, down_word: down58.id)
mediumPuzzle.cells.create(letter: 'S', index: 225, across_word: across61.id, down_word: down45.id)
mediumPuzzle.cells.create(letter: 'I', index: 226, across_word: across61.id, down_word: down42.id)
mediumPuzzle.cells.create(letter: 'P', index: 227, across_word: across61.id, down_word: down37.id)
mediumPuzzle.cells.create(letter: 'H', index: 228, across_word: across61.id, down_word: down55.id)
mediumPuzzle.cells.create(letter: 'O', index: 229, across_word: across61.id, down_word: down51.id)
mediumPuzzle.cells.create(letter: 'N', index: 230, across_word: across61.id, down_word: down46.id)
mediumPuzzle.cells.create(letter: '!', index: 231, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: '!', index: 232, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'A', index: 233, across_word: across62.id, down_word: down52.id)
mediumPuzzle.cells.create(letter: 'L', index: 234, across_word: across62.id, down_word: down57.id)
mediumPuzzle.cells.create(letter: 'T', index: 235, across_word: across62.id, down_word: down48.id)
mediumPuzzle.cells.create(letter: '!', index: 236, across_word: 0, down_word: 0)
mediumPuzzle.cells.create(letter: 'T', index: 237, across_word: across63.id, down_word: down44.id)
mediumPuzzle.cells.create(letter: 'O', index: 238, across_word: across63.id, down_word: down39.id)
mediumPuzzle.cells.create(letter: 'T', index: 239, across_word: across63.id, down_word: down40.id)
mediumPuzzle.cells.create(letter: 'O', index: 240, across_word: across63.id, down_word: down58.id)







